apiVersion: batch/v1
kind: Job
metadata:
  name: installplan-approver
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.4
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/approver

              echo "Approving operator install.  Waiting $SLEEP seconds to make sure the InstallPlan gets created first."
              sleep $SLEEP
              echo "Processing subscription '$OPERATOR_SUB_NAME'"

              installplan=$(oc get subscriptions.operators.coreos.com --field-selector metadata.name=${OPERATOR_SUB_NAME} -o jsonpath='{.items[0].status.installPlanRef.name}')

              echo "Check installplan approved status"
              oc get installplan $installplan -o jsonpath="{.spec.approved}"

              if [ "`oc get installplan $installplan -o jsonpath="{.spec.approved}"`" == "false" ]; then

                echo "Approving Subscription $OPERATOR_SUB_NAME with install plan $installplan"

                oc patch installplan $installplan --type=json -p='[{"op":"replace","path": "/spec/approved", "value": true}]'

              else
                echo "Install Plan '$installplan' already approved"
                fi
          imagePullPolicy: Always
          name: installplan-approver
          env:
            - name: SLEEP
              value: "60"
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccountName: installplan-approver-job
      terminationGracePeriodSeconds: 30